Implemented Swagger module
12pool/kanban pull request #55
Opened 2024-02-01 20:22 UTC by br4min

2024-02-01 22:17 UTC, Pawel1894 commented on backend/src/main.ts
> +    .setDescription('this is tne kanban API version 1.0')
Literówka w opisie

2024-02-01 22:28 UTC, Pawel1894 requested changes
Dodaj typy do dtos
https://docs.nestjs.com/openapi/types-and-parameters
kontrolery podzieliłbym na różne tagi żeby było łatwiej się odnaleźć
https://docs.nestjs.com/openapi/operations

2024-02-03 01:55 UTC, br4min commented on backend/src/main.ts
> +    .setDescription('this is tne kanban API version 1.0')
Literówka poprawiona ApiTags i ApiTypes dodane. Zmieniłem też numer wersji na 0.1 bo jednak do 1.0 to jeszcze trochę chyba za mało.

2024-02-03 09:24 UTC, Pawel1894 approved these changes

2024-02-03 10:03 UTC, merged